Gemfile, Gemfile.lock, app/models/product.rb, app/views/products/index.html.erb
=> gem pg search added

app/views/products/show.html.erb
exibicao-condicional-btn-edit-e-rm - resolvido e funcional
=> exibicao-condicional-btn-edit-e-rm - resolvido e funcional

app/controllers/products_controller.rb, app/views/products/index.html.erb
=> search working

.gitignore, Gemfile, Gemfile.lock, db/seeds.rb
Pessoal, primeira versão do seed!
=> seed added

app/views/products/index.html.erb, app/views/products/show.html.erb
=> index and show updated

db/seeds.rb
Após seed apresentou o erro ' undefined method `admin' for nil:NilClass '. 
Para resolve-lo, incluí ' admin: false ' na seed. Funcionou.
Aproveitando para deixar nossos perfis criados, para facilitar fase de testes.
Após testes, tudo funcional, nenhum conflito identificado.
=> admin default false on seed and profiles for Eugenia, Luanda e Wilson

app/controllers/orders_controller.rb, app/views/orders/index.html.erb
=> page orders criada

app/javascript/components/banner.js, app/javascript/packs/application.js, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb, package.json, yarn.lock
Adicionado typed.js.
Adicionado link para orders list no dropdown do navbar.
=> adicionado typed.js no banner e link para orders no nav bar

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
Adicionado link para o home no ícone do violão
=> home actived in navbar

app/views/products/show.html.erb
=> erro admin na show de products resolvido

app/controllers/orders_controller.rb, app/controllers/pages_controller.rb, app/views/pages/my_orders.html.erb, config/routes.rb, db/seeds.rb
Route my orders implementada. Código funcional.
=> my orders implemented

app/views/products/show.html.erb, app/views/shared/_navbar.html.erb
Nome do usuario aparece no navbar
=> alteracao de alguns links no navbar

app/policies/product_policy.rb
pequeno ajuste do destroy product, agora apenas para admins
=> ajustado código destroy para evitar a quegra em caso de order gerada

app/controllers/pages_controller.rb, app/controllers/products_controller.rb, app/views/pages/my_offers.html.erb, config/routes.rb
Funcionando. Sem controle da quantidade vendida
=> rota para mostrar ofertas do artista

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb, db/seeds.rb
Mudanças na home e no seed para ficar mais próximos do real
=> home and seed changes

app/views/products/show.html.erb
Info Product show the artist and stock
=> show product updated

app/controllers/orders_controller.rb, app/controllers/products_controller.rb, app/models/order.rb, app/views/orders/_form.html.erb, app/views/orders/new.html.erb, app/views/pages/my_orders.html.erb, app/views/products/show.html.erb, config/routes.rb
pegando a quantidade de produtos desejada pelo usuario
=> pegando a quantidade de produtos desejada pelo usuario

app/controllers/orders_controller.rb, app/controllers/products_controller.rb, app/models/order.rb, app/views/orders/_form.html.erb, app/views/orders/new.html.erb, app/views/pages/my_orders.html.erb, app/views/products/show.html.erb, config/routes.rb
Implementada redução do estoque após geração de order - funcional
=> Abatendo o stock

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb
Atualização das margens e do footer.
=> home uptaded

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
=> ajustes na home e na navbar

app/controllers/pages_controller.rb, app/controllers/products_controller.rb, app/views/pages/artist.html.erb, app/views/pages/artists.html.erb, config/routes.rb, db/migrate/20211101205017_add_seller_to_users.rb, db/schema.rb, db/seeds.rb
funcionando via:  http://localhost:3000/artists
=> teste de rotas para mostrar produtos por artista

app/views/devise/sessions/new.html.erb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
=> changes in home, navbar and login pages

app/controllers/products_controller.rb, app/views/pages/_set_photo.html.erb, app/views/pages/artist.html.erb, app/views/products/show.html.erb, db/migrate/20211101235929_add_img_url_to_products.rb, db/schema.rb, db/seeds.rb
Criada coluna para endereço da imagem (internet) e coloquei uma condicional para mostrar as fotos e funcionou para desfazer o bug - funcional
=> bug das fotos resolvido

app/controllers/pages_controller.rb
implementada dispensa de autenticacao para rotas artists e artist
=> dispensa de autenticacao para rotas artists e artist

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/pages/_home.scss, app/views/pages/artist.html.erb, app/views/pages/home.html.erb, app/views/pages/my_orders.html.erb, app/views/products/index.html.erb, app/views/shared/_navbar.html.erb, db/seeds.rb
pequenos ajustesbfrontend home, index de products
=> ajustes-frontend-home-index-de-products

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
Mudança na cor dos links login e sign in
=> links sign login changed to white

app/assets/stylesheets/components/_navbar.scss, app/views/devise/sessions/new.html.erb, app/views/shared/_navbar.html.erb
=> Login page buttons

app/views/pages/artists.html.erb
ajuste-frontend-artists - funcional
=> inseridos cards

app/assets/stylesheets/components/_navbar.scss, app/views/pages/artist.html.erb, app/views/pages/artists.html.erb, app/views/shared/_navbar.html.erb
criado id para mudar a cor de login e signup navbar
=> Navbar cor texto dos links

app/views/pages/artist.html.erb, app/views/pages/artists.html.erb
apenas ajustes de botoes - funcional
=> ajustados botoes das pages artists e artist

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/pages/_home.scss, app/views/pages/artists.html.erb, app/views/pages/home.html.erb, app/views/products/index.html.erb, config/initializers/cloudinary.rb, db/seeds.rb
substituidas url unsplash pelo cloudinary
=> substituidas url unsplash pelo cloudinary
